export const CREATE_CLIENT_ACCOUNT = "CREATE_CLIENT_ACCOUNT";
export const CREATE_PRPOVIDER_ACCOUNT = "CREATE_PRPOVIDER_ACCOUNT";
export const CONNECT_TO_CLIENT_ACCOUNT = "CONNECT_TO_CLIENT_ACCOUNT";
export const CONNECT_TO_PRPOVIDER_ACCOUNT = "CONNECT_TO_PROVIDER_ACCOUNT";
export const LOG_OUT = "LOG_OUT";